[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.25"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@octant-core/=lib/octant-v2-core/src/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config